title: Andrew Ryan
description: Personal website and academic portfolio
remote_theme: just-the-docs/just-the-docs

url: https://andrewjamesryan.github.io/final-project

# Navigation order
just_the_docs:
  navigation:
    - index.md
    - about.md
    - projects.md
    - resume.md
    - contact.md

aux_links:
  GitHub Repository: https://github.com/andrewjamesryan/final-project
