title: Andrew Ryan
description: Personal website and academic portfolio
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: "https://andrewjamesryan.github.io"
baseurl: "/final-project"

# Navigation order
just_the_docs:
  navigation:
    - index.md
    - about.md
    - projects.md
    - work.md
    - resume.md
    - contact.md

aux_links:
  GitHub Repository: https://github.com/andrewjamesryan/final-project

sass:
  load_paths:
    - _sass

just_the_docs:
  custom_css: custom.css
