title: "Andrew James Ryan"
description: "Final Project â€“ Code in Context"
remote_theme: just-the-docs/just-the-docs

baseurl: "/final-project"
url: "https://andrewjamesryan.github.io"

# Navigation structure
nav_order: 1

aux_links:
  "GitHub Repository":
    - "https://github.com/andrewjamesryan/final-project"
